### ISSUE TITLE
Gestion du fichier de configuration

### ISSUE THREAD

**Issue by NilsPonsard** [NilsPonsard/projetSpaceInvaders#13]
Il faudrait mettre un message si le fichier n'est pas trouvé et peut être le créer automatiquement

**Comment by NilsPonsard** [comment]
#14

**Comment by hugo-harkness** [comment]
https://github.com/NilsPonsard/projetSpaceInvaders/commit/57107c9a6fb3412d5cea7d6c04b49ce7ff028160
